---
title: "Comparing stringr to base R"
author: "Sara Stoudt"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

[Solving this issue](https://github.com/tidyverse/stringr/issues/266) for tidy-dev-day.


`str_c`

```{r}
str_c("Letter: ", letters)
paste("Letter: ",letters,sep="")
```

```{r}
str_c("Letter", letters, sep = ": ")
paste("Letter", letters, sep = ": ")
```

`str_conv`



`str_count`

```{r}
fruit <- c("apple", "banana", "pear", "pinapple")

str_count(fruit, "a")
str_count(fruit, "p")
str_count(fruit, "e")
str_count(c("a.", "...", ".a.a"), ".")


countCharOccurrences <- function(char, s) {
    s2 <- gsub(char,"",s)
    return (nchar(s) - nchar(s2))
}#https://techoverflow.net/2012/11/10/r-count-occurrences-of-character-in-string/
## maybe need to change this to length instead of nchar, see str_length

countCharOccurrences("a",fruit)
countCharOccurrences("p",fruit)
countCharOccurrences("e",fruit)
countCharOccurrences(".",c("a.", "...", ".a.a"))
```


```{r}
## difference
str_count(fruit, c("a", "b", "p", "p"))
str_count(c("a.", "...", ".a.a"), fixed("."))

lapply(c("a", "b", "p", "p"),countCharOccurrences,fruit)
countCharOccurrences(fixed("."),c("a.", "...", ".a.a"))
```


`str_detect`

```{r}
str_detect(fruit, "a")
grepl("a", fruit)

str_detect(fruit, "^a")
grepl("^a", fruit)

str_detect(fruit, "a$")
grepl("a$", fruit)

str_detect(fruit, "b")
grepl("b", fruit)

str_detect(fruit, "[aeiou]")
grepl("[aeiou]", fruit)
```

```{r}
## difference
str_detect("aecfg", letters)
grepl("aecfg", letters)

lapply(unlist(str_split("aecfg","")),function(x){grepl(x,letters)}) 
## TO DO: need to collaps via "or"
```


`str_dup`

```{r}
fruit <- c("apple", "pear", "banana")
str_dup(fruit, 2)
str_dup(fruit, 1:3)
str_c("ba", str_dup("na", 0:5))


#https://stackoverflow.com/questions/22359127/how-to-repeat-a-string-n-times-in-r
unlist(lapply(lapply(fruit,function(x){replicate(2,x)}),paste,collapse=""))

unlist(lapply(mapply(function(x,y){replicate(x,y)},1:3,fruit),paste,collapse=""))

paste("ba",unlist(lapply(lapply(0:5,function(x){replicate(x,"na")}),paste,collapse="")),sep="")
```

`str_extract`

```{r}
shopping_list <- c("apples x4", "bag of flour", "bag of sugar", "milk x2")
str_extract(shopping_list, "\\d")
str_extract(shopping_list, "[a-z]+")

#https://stackoverflow.com/questions/47678725/how-to-do-str-extract-with-base-r
```

`str_flatten`

```{r}
str_flatten(letters)
paste(letters,collapse="")

str_flatten(letters, "-")
paste(letters,"-",sep="",collapse="")
```

`str_glue`

```{r}
name <- "Fred"
age <- 50
anniversary <- as.Date("1991-10-12")
str_glue(
"My name is {name}, ",
"my age next year is {age + 1}, ",
"and my anniversary is {format(anniversary, '%A, %B %d, %Y')}."
)


paste("My name is ",eval(name),", my age next year is ",eval(age+1),", and my anniversary is ",eval(format(anniversary, '%A, %B %d, %Y')),".",sep="")
```

`str_length`

```{r}
str_length(letters)
nchar(letters)

str_length(NA)
nchar(NA)

str_length(c("i", "like", "programming", NA))
nchar(c("i", "like", "programming", NA))
```

```{r}
## difference
str_length(factor("abc"))
nchar(factor("abc")) ## Error in nchar(factor("abc")) : 'nchar()' requires a character vector
```

```{r}
u1 <- "\u00fc"
u2 <- stringi::stri_trans_nfd(u1)
# The print the same:
u1
u2
# But have a different length
str_length(u1)
str_length(u2)
# Even though they have the same number of characters
str_count(u1)
str_count(u2)

nchar(u1) ## matches length not count
nchar(u2)

length(u1) ## weird
length(u2)
```


`str_locate`

```{r}
fruit <- c("apple", "banana", "pear", "pineapple")
str_locate(fruit, "$")
# "If the match is of length 0, (e.g. from a special match like $) end will be one character less than start."

str_locate(fruit, "a")
str_locate(fruit, "e")
str_locate(fruit, "ap") ## adding this

str_locate(fruit, c("a", "b", "p", "p"))

gregexpr("$",fruit) ## ## get stuff out

gregexpr("a",fruit)

gregexpr("e",fruit) ## -1 is the NA
gregexpr("ap",fruit)

mapply(gregexpr,c("a", "b", "p", "p"),fruit)
```

`str_match`


`str_order`

```{r}
str_order(letters)
str_sort(letters)

order(letters)
sort(letters)
```

```{r}
str_order(letters, locale = "haw") ## vowels come first
str_sort(letters, locale = "haw")
## no locale capability in order, sort
```

```{r}
x <- c("100a10", "100a5", "2b", "2a")
str_sort(x)
str_sort(x, numeric = TRUE)

sort(x)
## no numeric capability in sort
```

`str_pad`

```{r}
rbind(
str_pad("hadley", 30, "left"),
str_pad("hadley", 30, "right"),
str_pad("hadley", 30, "both")
)

sprintf("%30s","hadley")
sprintf("%-30s","hadley")

leftover=30-nchar("hadley")
leftpad=nchar("hadley")+floor(leftover/2)

rbind(sprintf("%30s","hadley"),
sprintf("%-30s","hadley"),
sprintf("%-30s",sprintf(paste("%",leftpad,"s",sep=""),"hadley"))
)
```

```{r}
str_pad(c("a", "abc", "abcdef"), 10)

str_pad("a", c(5, 10, 20))

str_pad("a", 10, pad = c("-", "_", " "))

str_pad("hadley", 3) # Longer strings are returned unchanged


sprintf("%10s",c("a", "abc", "abcdef"))

unlist(lapply(c(5, 10, 20),function(x){sprintf(paste("%",x,"s",sep=""),"a")}))


unlist(lapply(c("-", "_", " "),function(x){gsub(" ",x,sprintf("%10s","a"))}))


sprintf("%3s","hadley")
```


`str_remove`

```{r}
fruits <- c("one apple", "two pears", "three bananas")
str_remove(fruits, "[aeiou]")
str_remove_all(fruits, "[aeiou]")

sub("[aeiou]","",fruits)
gsub("[aeiou]","",fruits)
```

`str_replace`

```{r}
str_replace(fruits, "[aeiou]", "-")
str_replace_all(fruits, "[aeiou]", "-")

sub("[aeiou]","-",fruits)
gsub("[aeiou]","-",fruits)
```

```{r}
str_replace(fruits, "([aeiou])", "")
str_replace(fruits, "([aeiou])", "\\1\\1")

sub("([aeiou])","",fruits)
sub("([aeiou])","\\1\\1",fruits)
```

```{r}
str_replace(fruits, "[aeiou]", c("1", "2", "3"))
str_replace(fruits, c("a", "e", "i"), "-")


mapply(function(x,y){sub("[aeiou]",x,y)},c(1,2,3),fruits)

unname(mapply(function(x,y){sub(x,"-",y)},c("a","e","i"),fruits))
```

```{r}
## TO DO
str_replace_all(fruits, "[aeiou]", toupper)

str_replace_all(fruits, "b", NA_character_)
```


`str_replace_na`

```{r}
str_replace_na(c(NA, "abc", "def"))

sub(NA,"NA",c(NA, "abc", "def")) ## doesn't work

input=c(NA, "abc", "def")
ifelse(is.na(input),"NA",input)
```

`str_split`

```{r}
fruits <- c(
"apples and oranges and pears and bananas",
"pineapples and mangos and guavas"
)

str_split(fruits, " and ")

strsplit(fruits, " and ")
```

```{r}
str_split(fruits, " and ", simplify = T)

#https://stackoverflow.com/questions/17308551/do-callrbind-list-for-uneven-number-of-column
output=strsplit(fruits, " and ")
outputDF=lapply(output,function(x){as.data.frame(t(x),stringsAsFactors=F)})
simplified = plyr::rbind.fill(outputDF)
simplified = as.matrix(simplified)
simplified[which(is.na(simplified))]=""
unname(simplified)
```

```{r}
# Specify n to restrict the number of possible matches
str_split(fruits, " and ", n = 3)
str_split(fruits, " and ", n = 2)
# If n greater than number of pieces, no padding occurs
str_split(fruits, " and ", n = 5)
# Use fixed to return a character matrix
str_split_fixed(fruits, " and ", 3)
## same as str_split(fruits, " and ", 3, simplify = T)
str_split_fixed(fruits, " and ", 4)
```

`str_sub`

```{r}
hw <- "Hadley Wickham"

str_sub(hw, 1, 6)
substr(hw, 1,6)

str_sub(hw, end = 6)
## no default start and stop, need both

str_sub(hw, 8, 14)
substr(hw,8,14)

str_sub(hw, 8)
## no default start and stop, need both

str_sub(hw, c(1, 8), c(6, 14))
mapply(function(x,y){substr(hw,x,y)},c(1,8),c(6,14))
```

```{r}
# Negative indices
str_sub(hw, -1)
str_sub(hw, -7)
str_sub(hw, end = -7)


substr(hw,nchar(hw),nchar(hw))
substr(hw,nchar(hw)-6,nchar(hw))
```

```{r}
# Alternatively, you can pass in a two colum matrix, as in the
# output from str_locate_all
pos <- str_locate_all(hw, "[aeio]")[[1]]
str_sub(hw, pos)
str_sub(hw, pos[, 1], pos[, 2])

apply(pos,1,function(x){substr(hw,x[1],x[2])})
```

```{r}
# Vectorisation
str_sub(hw, seq_len(str_length(hw)))
str_sub(hw, end = seq_len(str_length(hw)))

unlist(lapply(seq_len(str_length(hw)),function(x){substr(hw,1,x)}))

```

```{r}
# Replacement form
x <- "BBCDEF"
str_sub(x, 1, 1) <- "A"; x
str_sub(x, -1, -1) <- "K"; x
str_sub(x, -2, -2) <- "GHIJ"; x
str_sub(x, 2, -2) <- ""; x

x <- "BBCDEF"
substr(x,1,1) <- "A"; x
substr(x, nchar(x),nchar(x)) <- "K"; x
substr(x, nchar(x)-1,nchar(x)-1) <- "GHIJ"; x ## different
substr(x, 2, nchar(x)-1) <- ""; x
```

```{r}
# If you want to keep the original if some argument is NA,
# use omit_na = TRUE
x1 <- x2 <- x3 <- x4 <- "AAA"
str_sub(x1, 1, NA) <- "B"
str_sub(x2, 1, 2) <- NA
str_sub(x3, 1, NA, omit_na = TRUE) <- "B"
str_sub(x4, 1, 2, omit_na = TRUE) <- NA
x1; x2; x3; x4

x1 <- x2 <- x3 <- x4 <- "AAA"

substr(x1,1,NA) <- "B"
substr(x2,1,2) <- NA ## different
substr(x3, 1, NA) <- "B"
str_sub(x4, 1, 2, omit_na = TRUE) <- NA

x1; x2; x3; x4
```


`str_subset`

```{r}
fruit <- c("apple", "banana", "pear", "pinapple")
str_subset(fruit, "a")
str_which(fruit, "a")

grep("a", fruit, value = TRUE)
grep("a", fruit)
```

```{r}
str_subset(fruit, "^a")
str_subset(fruit, "a$")
str_subset(fruit, "b")
str_subset(fruit, "[aeiou]")

grep("^a", fruit, value = TRUE)
grep("a$", fruit, value = TRUE)
grep("b", fruit, value = TRUE)
grep("[aeiou]", fruit, value = TRUE)


# Missings never match
str_subset(c("a", NA, "b"), ".")
str_which(c("a", NA, "b"), ".")

grep( ".", c("a", NA, "b"), value = TRUE)
grep( ".", c("a", NA, "b"))
```


`str_trim`
`str_trunc`
`str_view`
`str_wrap`
